<h1>Laboratory work №2</h1>
<h2>Abylgaziev Kairat AIN-1-21</h2>

In [1]:
import numpy as np

### 1.1. Создайте одномерный массив my_array, в котором по порядку все числа до 100, кратные 5

In [2]:
my_array = np.arange(5, 101, 5)
my_array

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

### 2.1. Из полученного массива получить массив с кратными 10 числами

In [3]:
my_array_10 = my_array[my_array % 10 == 0]
my_array_10

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

### 3.1. Получить двумерный массив с двумя столбцами

In [4]:
my_2d_array = my_array.reshape(-1, 2)
my_2d_array

array([[  5,  10],
       [ 15,  20],
       [ 25,  30],
       [ 35,  40],
       [ 45,  50],
       [ 55,  60],
       [ 65,  70],
       [ 75,  80],
       [ 85,  90],
       [ 95, 100]])

### 4.1. Получите набор my_second_array, в котором все элементы меньше предыдущего исходного на 5

In [5]:
my_second_array = my_2d_array - 5
my_second_array

array([[ 0,  5],
       [10, 15],
       [20, 25],
       [30, 35],
       [40, 45],
       [50, 55],
       [60, 65],
       [70, 75],
       [80, 85],
       [90, 95]])

### 5.1. Соедините массивы, полученные в п. 3.1 и 4.1, горизонтально. Используйте .T для транспонирования матрицы.

In [6]:
combined_array = np.hstack((my_2d_array, my_second_array))
combined_array

array([[  5,  10,   0,   5],
       [ 15,  20,  10,  15],
       [ 25,  30,  20,  25],
       [ 35,  40,  30,  35],
       [ 45,  50,  40,  45],
       [ 55,  60,  50,  55],
       [ 65,  70,  60,  65],
       [ 75,  80,  70,  75],
       [ 85,  90,  80,  85],
       [ 95, 100,  90,  95]])

### 6.1. Разделите 2 и 3 строку на 4 верхних строки my_array. Используйте .T для транспонирования матрицы

In [31]:
combined_array2 = (combined_array[1:3] / my_array[:4]).T

combined_array2 =  
print(combined_array[1:3])
my_array[:4]

[[15 20 10 15]
 [ 5 10  0  5]]


array([ 5, 10, 15, 20])

### 7.1. Оставить только те значения, которые не изменились после деления

In [29]:
filtered_array = combined_array2[combined_array2[:, 0] == combined_array[:4][:, 1]]
filtered_array

array([], shape=(0, 2), dtype=float64)

### 8.1. Снова получить трехстрочный двумерный массив и поменять местами первую и третью строки

In [9]:
final_array = combined_array[:3]
final_array[[0, 2]] = final_array[[2, 0]]
final_array

array([[25, 30, 20, 25],
       [15, 20, 10, 15],
       [ 5, 10,  0,  5]])

### 9.1. Получить среднее, медиану и стандартное отклонение для каждой строки

In [10]:
mean_values = np.mean(final_array, axis=1)
median_values = np.median(final_array, axis=1)
std_deviation = np.std(final_array, axis=1)
for i in range(len(median_values)):
    print(f"Строка {i+1}: Среднее = {mean_values[i]}, Медиана = {median_values[i]}, Стандартное отклонение = {std_deviation[i]}")

Строка 1: Среднее = 25.0, Медиана = 25.0, Стандартное отклонение = 3.5355339059327378
Строка 2: Среднее = 15.0, Медиана = 15.0, Стандартное отклонение = 3.5355339059327378
Строка 3: Среднее = 5.0, Медиана = 5.0, Стандартное отклонение = 3.5355339059327378


### 10.1. Сделать нормализацию на максимальное значение вдоль строк, поделив каждый элемент массива на max() вдоль строк

In [11]:
normalized_array = final_array / final_array.max(axis=1, keepdims=True)
normalized_array

array([[0.83333333, 1.        , 0.66666667, 0.83333333],
       [0.75      , 1.        , 0.5       , 0.75      ],
       [0.5       , 1.        , 0.        , 0.5       ]])

# 2.	Использование команд библиотеки pandas

In [12]:
import pandas as pd

### 2.1.	Импортируйте данные из файла “Global Population Trends(2016-2022).csv”. 

In [13]:
file_path = 'Global Population Trends(2016-2022).csv'
df = pd.read_csv(file_path)

### 2.2: Считайте несколько первых записей таблицы

In [14]:
print(df.head())

       Country  Year Total Population Urban Population Rural Population  \
0  Afghanistan  2017                -                -                -   
1  Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2  Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3  Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4  Afghanistan  2021       40,099,462       10,551,772       29,547,690   

  Population Density Life Expectancy  Birth Rate  Death Rate Fertility Rate  \
0                 55            63.0      37.342       7.027          5.129   
1                 56            63.0      36.927       6.981          5.002   
2                 58            64.0      36.466       6.791           4.87   
3                 60            63.0      36.051       7.113           4.75   
4                  -            62.0      35.842       7.344          4.643   

  Infant Mortality Rate Growth Rate  
0                  49.4           - 

### 2.3: Определите размерность фрейма

In [15]:
print(df.shape)

(1073, 12)


### 2.4: Выведите названия заголовков столбцов

In [16]:
print(df.columns)

Index(['Country', 'Year', 'Total Population', 'Urban Population',
       'Rural Population', 'Population Density', 'Life Expectancy',
       'Birth Rate', 'Death Rate', 'Fertility Rate', 'Infant Mortality Rate',
       'Growth Rate'],
      dtype='object')


### 2.5: Получите описание всех переменных (полей)

In [17]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1073 entries, 0 to 1072
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   Country                1073 non-null   object 
 1   Year                   1073 non-null   int64  
 2   Total Population       1073 non-null   object 
 3   Urban Population       1073 non-null   object 
 4   Rural Population       1073 non-null   object 
 5   Population Density     1073 non-null   object 
 6   Life Expectancy        1073 non-null   object 
 7   Birth Rate             1073 non-null   float64
 8   Death Rate             1073 non-null   float64
 9   Fertility Rate         1073 non-null   object 
 10  Infant Mortality Rate  1073 non-null   object 
 11  Growth Rate            1073 non-null   object 
dtypes: float64(2), int64(1), object(9)
memory usage: 100.7+ KB
None


### 2.6: Удалите строки, не содержащие значения в столбце «Total Population»

In [18]:
df = df[df['Total Population'] != '-']

### 2.7: Получите описательную статистику по переменным

In [19]:
print(df.describe())

              Year  Birth Rate  Death Rate
count   864.000000  864.000000  864.000000
mean   2019.500000   18.548384    7.889123
std       1.118682    9.887518    3.041385
min    2018.000000    0.000000    0.000000
25%    2018.750000   10.500000    6.116500
50%    2019.500000   15.628500    7.453500
75%    2020.250000   25.565000    9.385000
max    2021.000000   46.127000   21.700000


### 2.8: Выполните сортировку данных по нескольким критериям

In [20]:
# сортировка по столбцу 'Year' в порядке убывания
df = df.sort_values(by=['Year'], ascending=False)

### 2.9: Выведите название страны с максимальной численностью населения

In [25]:
# df['Total Population'] = df['Total Population'].str.replace(',', '').astype(int)
max_population_index = df['Total Population'].idxmax()
max_population_country = df.loc[max_population_index]['Country']
print('Страна с максимальной численностью населения:', max_population_country)

Страна с максимальной численностью населения: China


### 2.10: Выведите название страны с минимальной численностью населения

In [26]:
min_population_index = df['Total Population'].idxmin()
min_population_country = df.loc[min_population_index]['Country']
print('Страна с минимальной численностью населения:', min_population_country)


Страна с минимальной численностью населения: Tuvalu


### 2.11: Экспорт фрейма в MS Excel

In [ ]:
excel_file_path = 'Global_Population_Trends.xlsx'
df.to_excel(excel_file_path, index=False)
print(f"Фрейм успешно экспортирован в {excel_file_path}")